using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;

namespace BEAR
{
    /// <summary>
    /// Variables Classes are constants used by BEAR.  These variables could be placed in a database file and given an interface and be made into user defined fields.
    /// </summary>
    public class VariablesExceptionRates
    {
        public static String ERROR_LOG_FILE_NAME = "\\\\bmelite\\elite\\work\\logs\\BEAR\\ExceptionRatesErrorLog.log"; ///<Error log file location

        public static String ERROR_MESSAGE_PARAMETERS_NOT_COMPLETE = "<ul>Please Enter at least one of the following <li>a Billing TKID,</li><li>a Billing Specialist</li><li>a Client Number, OR</li><li>a Billing Office</li></ul>"; ///<Message shown when not enough filters have been entered on Exception Rate Parameter Screen

        public static String HOME_PAGE = "parameters.aspx"; ///<Application's Home Page
        public static String DATA_PAGE = "exceptionRates.aspx"; ///<Application's page called after parameters have been entered
        public static String EMAIL_PAGE = "email.aspx"; ///<Application's page to send email.  For Admin access only.
        public static String HOME_PAGE_DIRECTORY = "exceptionRates/"; ///<BEAR Directory of Application

        public static int MINIMUM_WIDTH_MATTER = 190; ///<sets the minimum width of the matter description column

        public static String DATA_DIV_CUSTOM_STYLE = "height: 520px"; ///<Sets the height of the data results grid.  asp:GridView = dataGridView
        public static int DATA_PAGE_SIZE = 15; ///<number of rows on a page

        public static String TOOLTIP_SUBMIT_BUTTON = "View Exception Rates Application with the above parameters<br /><br />" +
                                                    "<em>Pressing the Enter Key <br>has same effect as clicking this Submit button<em>"; ///<Tool Tip Text 
        public static String TOOLTIP_PRINT_BUTTON = "Printable Version<br><br><em>After the Report displays,<br>clicking on the Orange Report Title will return to this application.</em>";
        public static String TOOLTIP_SAVE_BUTTON = "Save Changes<br><br><em>Pressing the Enter Key <br>has same effect as clicking this Update button<em>"; ///<Tool Tip Text 
        public static String TOOLTIP_RERUN_BUTTON = "Click this button to <br>change the Application Parameters"; ///<Tool Tip Text 
        public static String TOOLTIP_EXIT_BUTTON = "Exit this application<br> and close the browser"; ///<Tool Tip Text 
        public static String TOOLTIP_SEARCH_TKID_BUTTON = "Click to Search Billing Attorneys"; ///<Tool Tip Text 
        public static String TOOLTIP_SEARCH_CLIENT_BUTTON = "Click to Search Clients"; ///<Tool Tip Text 

        public static String REPORT_SERVICES_PRINT_NAME = "ExceptionRates";///<Reporting Services Report that is called when the Print Button is clicked
        public static String REPORT_FOLDER = "/Financial%20Accounting/Bear/ExceptionRates"; ///<Reporting Services Folder

        /// <summary>
        /// EMAIL_BODY_[DESCRIPTION] variables are used to build the email that is sent by the admin functionality in the Exception Rate Application
        /// There are a total of four default emails that are generated by the application:
        ///    - Initial email - sent to legal personnel requesting exception rate be entered
        ///        -# Default: (example, non-McKee)
        ///        -# Alternate: (example, McKee)
        ///    - Reminder email - reminder to enter the exception rates
        ///        -# Default
        ///        -# Alternate
        /// within the Strings holding the email information, HTML is entered to format the message.
        /// </summary>
        public static String EMAIL_BODY_OPENING_LINE_DEFAULT = "The Link below will take you to a list of your clients and matters with special rates and discounts.\n\n<br /><br />";

        public static String EMAIL_BODY_OPENING_LINE_ALTERNATE = "The Link below will take you to a list of your clients and matters with programmed fee agreements.\n\n<br /><br />";

        public static String EMAIL_BODY_DEFAULT = 
                                                  "<p><b>\n\n" 
                                                  + "Directions on how to use this online report:"
                                                  + "\n\n</b>\n<ul style='line-height: 1.4'><li style='margin-bottom:12px'>\n\n"
                                                  + "This report shows you the billing rates we used in 2009 for your clients and matters. The columns of information for your reference are the discounts or billing rates we used to bill your work last year, and 2009 and 2010 firm standard billing rates."
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "Pay specific attention to the 'current special rate', 'rate code' and 'discount %' column and please tell us if there are any changes or deletions. You can use the 'Notes' column for that communication. If you have any questions about what we are billing your client, please contact your Billing Specialist."
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "Please update us with your 2010 client billing rates or percentage discount. "
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "If there are no changes to the agreement and you are planning on extending the agreement through 2010, check the \"No Change\" button next to the row of rate information. "
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "If you share billing of a client with another partner, we assume you are working together on negotiating new rates with the client and you may add that Relationship partner name in the \"Notes\" section. "
                                                  + "\n\n</li></ul>\n</p>\n<p>\n<center>"
                                                  + "<img src=\"http://" + Environment.MachineName.ToString() + "/bear/exceptionRates/email_image.jpg\" alt=\"\" />"  
                                                  + "</center>\n</p>\n<p>\n\n"
                                                  + "If you have any questions about the information on this report or would like someone to walk you through the program, please contact your Billing Specialist."
                                                  + "\n\n<ul style='line-height: 1.4'><li>\n\n"
                                                  + "We would like all rate updates by" 
                                                  + "\n\n<span style='font-weight:bold;'>\n\n"
                                                  + "January 26th."
                                                  + "\n\n</span>\n\n<br /><br />\n\n<span style='font-weight:bold;'>\n<center>\n\n"
                                                  + "As a reminder, any discounts or special rates that are over 10% off standard rates, need to be approved by the Committee on Client Engagement PAL or the full Committee, if 2009 billings were over $200k, before presenting to your client."
                                                  + "\n\n</center>\n</span>\n"
                                                  ;                                                  

        public static String EMAIL_BODY_ALTERNATE =
                                                  "<p><b>\n\n" 
                                                  + "Directions on how to use this online report:"
                                                  + "\n\n</b>\n<ul style='line-height: 1.4'><li style='margin-bottom:12px'>\n\n"
                                                  + "This report shows you the billing rates we used in 2009, for your clients and matters. The columns of information for your reference are discounts or billing rates we used to bill your work last year, and 2009 and 2010 firm standard billing rates."
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "Pay specific attention to the 'current special rate', 'rate code' and 'discount %' column and please tell us if there are any changes or deletions. You can use the 'Notes' column for that communication. If you have any questions about what we are billing your client, please contact your Billing Manager."
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "Please update us with your 2010 client billing rates or percentage discount."
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "If there are no changes to the agreement and you are planning on extending the agreement through 2010, check the \"No Change\" button next to the row of rate information."
                                                  + "\n\n</li><li style='margin-bottom:12px'>\n\n"
                                                  + "If you share billing of a client with another partner, we assume you are working together on negotiating new rates with the client and you may add that Relationship partner name in the \"Notes\" section."
                                                  + "\n\n</li></ul>\n</p>\n<p>\n<center>"
                                                  + "<img src=\"http://" + Environment.MachineName.ToString() + "/bear/exceptionRates/email_image.jpg\" alt=\"\" />"  
                                                  + "</center>\n</p>\n<p>\n\n"
                                                  + "If you have any questions about the information on this report or would like someone to walk you through the program, please contact your Billing Manager."
                                                  + "\n\n<ul style='line-height: 1.4'><li>\n\n"
                                                  + "We would like all rate updates by" 
                                                  + "\n\n<span style='font-weight:bold;'>\n\n"
                                                  + "January 26th."
                                                  + "\n\n</span>\n\n<br /><br />\n\n<span style='font-weight:bold;'>\n<center>\n\n"
                                                  + "As a reminder, any discounts or special rates that are over 10% off standard rates, need to be approved by the Committee on Client Engagement PAL or the full Committee, if 2009 billings were over $200k, before presenting to your client."
                                                  + "\n\n</center>\n</span>\n"
                                                  ;



        public static String EMAIL_BODY_OPENING_LINE_REMINDER_DEFAULT = "Tuesday, 1/26/10 was the deadline for advisements regarding your special rates for 2010.  As of today, we have not received your information and need to program the new rates for your 2010 work.  Please keep in mind we will be running your January proformas early next week and need your exception rates submitted by Monday 2/1/10.   Should you have any questions, please call your Billing Specialist." +
                                                                    "\n\n<br /><br />\n\n" +
                                                                    "The Link below will take you to a list of your clients and matters with special rates and discounts." +
                                                                    "\n\n<br /><br />";


        public static String EMAIL_BODY_OPENING_LINE_REMINDER_ALTERNATE = "Tuesday, 1/26/10 was the deadline for advisements regarding your special rates for 2010.  As of today, we have not received your information and need to program the new rates for your 2010 work.  Please keep in mind we will be running your January proformas early next week and need your exception rates submitted by Monday 2/1/10.   Should you have any questions, please call your Billing Manager or Supervisor." +
                                                                    "\n\n<br /><br />\n\n" +
                                                                    "The Link below will take you to a list of your clients and matters with special rates and discounts." +
                                                                    "\n\n<br /><br />";



        public static String EMAIL_BODY_REMINDER_DEFAULT = "<br /><b>"
                                                  + "Directions on how to use this online report:"
                                                  + "</b><ul style='line-height: 1.4'><li>\n\n"
                                                  + "This report shows you the billing rates we used in 2009 for your clients and matters. The columns of information for your reference are the discounts or billing rates we used to bill your work last year, and 2009 and 2010 firm standard billing rates."
                                                  + "\n\n</li><li>\n\n"
                                                  + "Pay specific attention to the 'current special rate', 'rate code' and 'discount %' column and please tell us if there are any changes or deletions. You can use Notes column for that communication. If you have any questions about what we are billing your client, please contact your Billing Specialist."
                                                  + "\n\n</li><li>\n\n"
                                                  + "Please update us with your 2010 client billing rates or percentage discount."
                                                  + "\n\n</li><li>\n\n"
                                                  + "If there are no changes to the agreement and you are planning on extending the agreement through 2010, check the \"No Change\" button next to the row of rate information."
                                                  + "\n\n</li><li>\n\n"
                                                  + "If you share billing of a client with another partner, we assume you are working together on negotiating new rates with the client and you may add that Relationship partner name in the \"Notes\" section."
                                                  + "\n\n</li>"
                                                  ;

        public static String EMAIL_BODY_REMINDER_ALTERNATE = "<br /><b>"
                                                  + "Directions on how to use this online report:"
                                                  + "</b><ul style='line-height: 1.4'><li>\n\n"
                                                  + "This report shows you the billing rates we used in 2009 for your clients and matters. The columns of information for your reference are the discounts or billing rates we used to bill your work last year, and 2009 and 2010 firm standard billing rates."
                                                  + "\n\n</li><li>\n\n"
                                                  + "Pay specific attention to the 'current special rate', 'rate code' and 'discount %' column and please tell us if there are any changes or deletions. You can use Notes column for that communication. If you have any questions about what we are billing your client, please contact your Billing Manager or Supervisor."
                                                  + "\n\n</li><li>\n\n"
                                                  + "Please update us with your 2010 client billing rates or percentage discount."
                                                  + "\n\n</li><li>\n\n"
                                                  + "If there are no changes to the agreement and you are planning on extending the agreement through 2010, check the \"No Change\" button next to the row of rate information."
                                                  + "\n\n</li><li>\n\n"
                                                  + "If you share billing of a client with another partner, we assume you are working together on negotiating new rates with the client and you may add that Relationship partner name in the \"Notes\" section."
                                                  + "\n\n</li>"
                                                  ;



        private string variableTkid = "";
        public string tkid
        {
            get
            {
                return variableTkid;
            }
            set
            {
                variableTkid = value;
            }
        }



    }
}
